version: "3.2"
services:
  ipld-eth-beacon-db:
    hostname: ipld-eth-beacon-db
    env_file:
      - docker.env
    restart: always
    build:
      dockerfile: ../ipld-eth-beacon-db/Dockerfile
      context: ../ipld-eth-beacon-db
    image: cerc/ipld-eth-beacon-db:local
    healthcheck:
      test: ["CMD", "nc", "-v", "localhost", "5432"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - vdb_db_eth-beacon_db:/var/lib/postgresql/data
    ports:
      - "5432"
    command: ["postgres", "-c", "log_min_duration_statement=250"]

  ipld-eth-beacon-indexer:
    hostname: ipld-eth-beacon-indexer
    env_file:
      - docker.env
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      - ipld-eth-beacon-db
    image: cerc/ipld-eth-beacon-indexer:local

volumes:
  vdb_db_eth-beacon_db:
