name: Test Application On PR

on:
  workflow_dispatch:
    inputs:
      stack-orchestrator-ref:
        description: "The branch, commit or sha from stack-orchestrator to checkout"
        required: false
        default: "main"
      ipld-ethcl-db-ref:
        description: "The branch, commit or sha from ipld-ethcl-db to checkout"
        required: false
        default: "main"
      ssz-data-ref:
        description: "The branch, commit or sha from ssz-data to checkout"
        required: false
        default: "main"
  pull_request:
    paths:
      - "!**.md"
      - "!.gitignore"
      - "!LICENSE"
      - "!.github/workflows/**"
      - ".github/workflows/on-pr.yml"
      - ".github/workflows/tests.yml"
      - "**"
  schedule:
    - cron: '0 13 * * *' # Must be single quotes!!

jobs:
  trigger-tests:
    uses: ./.github/workflows/generic-testing.yml
    with:
      stack-orchestrator-ref: ${{ github.event.inputs.stack-orchestrator-ref }}
      ipld-ethcl-db-ref: ${{ github.event.inputs.ipld-ethcl-db-ref }}
      ssz-data-ref: ${{ github.event.inputs.ssz-data-ref }}
    secrets:
      GHA_KEY: ${{secrets.GHA_KEY}}
  system-testing:
    uses: ./.github/workflows/system-tests.yml
    with:
      stack-orchestrator-ref: ${{ github.event.inputs.stack-orchestrator-ref }}
      ipld-ethcl-db-ref: ${{ github.event.inputs.ipld-ethcl-db-ref }}
    secrets:
      GHA_KEY: ${{secrets.GHA_KEY}}
      BC_ADDRESS: ${{secrets.BC_ADDRESS}}
