name: Publish Docker image
on:
  release:
    types: [published, edited]
jobs:
  trigger-tests:
    uses: ./.github/workflows/generic-testing.yml
    with:
      stack-orchestrator-ref: ${{ github.event.inputs.stack-orchestrator-ref }}
      ipld-eth-beacon-db-ref: ${{ github.event.inputs.ipld-eth-beacon-db-ref }}
      ssz-data-ref: ${{ github.event.inputs.ssz-data-ref }}
    secrets:
      GHA_KEY: ${{secrets.GHA_KEY}}
  system-testing:
    uses: ./.github/workflows/system-tests.yml
    with:
      stack-orchestrator-ref: ${{ github.event.inputs.stack-orchestrator-ref }}
      ipld-eth-beacon-db-ref: ${{ github.event.inputs.ipld-eth-beacon-db-ref }}
    secrets:
      GHA_KEY: ${{secrets.GHA_KEY}}
      BC_ADDRESS: ${{secrets.BC_ADDRESS}}
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    needs:
      - trigger-tests
      - system-testing
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
      - name: Run docker build
        run: make docker-build
      - name: Tag docker image
        run: docker tag cerc-io/ipld-eth-beacon-indexer git.vdb.to/cerc-io/ipld-eth-beacon-indexer/ipld-eth-beacon-indexer:${{steps.vars.outputs.sha}}
      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://git.vdb.to -u cerccicd --password-stdin
      - name: Docker Push
        run: docker push git.vdb.to/cerc-io/ipld-eth-beacon-indexer/ipld-eth-beacon-indexer:${{steps.vars.outputs.sha}}
#  push_to_registries:
#    name: Push Docker image to Docker Hub
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Get the version
#        id: vars
#        run: |
#          echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
#          echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})
#      - name: Docker Login to Github Registry
#        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://git.vdb.to -u cerccicd --password-stdin
#      - name: Docker Pull
#        run: docker pull git.vdb.to/cerc-io/ipld-eth-beacon-indexer/ipld-eth-beacon-indexer:${{steps.vars.outputs.sha}}
#      - name: Docker Login to Docker Registry
#        run: echo ${{ secrets.VULCANIZEJENKINS_PAT }} | docker login -u vulcanizejenkins --password-stdin
#      - name: Tag docker image
#        run: docker tag git.vdb.to/cerc-io/ipld-eth-beacon-indexer/ipld-eth-beacon-indexer:${{steps.vars.outputs.sha}} cerc-io/ipld-eth-beacon-indexer:${{steps.vars.outputs.tag}}
#      - name: Docker Push to Docker Hub
#        run: docker push cerc-io/ipld-eth-beacon-indexer:${{steps.vars.outputs.tag}}
