name: Test Application Manually

on:
  workflow_dispatch:
    inputs:
      foundry-test-ref:
        description: "The branch, commit or sha from foundry-test to checkout"
        required: false
        default: "main"
      ipld-eth-db-ref:
        description: "The branch, commit or sha from ipld-eth-db to checkout"
        required: false
        default: "main"

jobs:
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker build
        run: make docker-build
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    env:
      GOPATH: /tmp/go
    steps:
      - name: Create GOPATH
        run: mkdir -p /tmp/go

      - uses: actions/checkout@v2
        with:
          path: "./ipld-ethcl-indexer"

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.foundry-test-ref }}
          path: "./foundry-test/"
          repository: vulcanize/foundry-test
          fetch-depth: 0

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ipld-eth-db-ref }}
          repository: vulcanize/ipld-eth-db
          path: "./ipld-eth-db/"
          fetch-depth: 0

      - name: Create config file
        run: |
          echo vulcanize_ipld_eth_db=$GITHUB_WORKSPACE/ipld-eth-db/ > ./config.sh
          echo vulcanize_ipld_ethcl_indexer=$GITHUB_WORKSPACE/ipld-ethcl-indexer >> ./config.sh
          cat ./config.sh

      - name: Run docker compose
        run: |
          docker-compose  \
          -f "$GITHUB_WORKSPACE/foundry-test/docker/local/docker-compose-db.yml" \
          -f "$GITHUB_WORKSPACE/foundry-test/docker/latest/docker-compose-lighthouse.yml" \
          --env-file ./config.sh \
          up -d --build

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
          check-latest: true

      - name: Install packages
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Run the tests
        run: |
          cd ipld-ethcl-indexer
          ls go/
          go vet ./...
          go fmt ./...
          ./go/bin/ginko -r

#          export GOPATH=$(echo $GOBIN | rev | cut -d "/" -f 2- | rev)
