name: Publish Docker image
on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      stack-orchestrator-ref:
        description: "The branch, commit or sha from stack-orchestrator to checkout"
        required: false
        default: "7fb664270a0ba09e2caa3095e8c91f3fdb5b38af"
      ipld-eth-beacon-db-ref:
        description: "The branch, commit or sha from ipld-eth-beacon-db to checkout"
        required: false
        default: "3dfe416302d553f8240f6051c08a7899b0e39e12"
      ssz-data-ref:
        description: "The branch, commit or sha from ssz-data to checkout"
        required: false
        default: "main"
  pull_request:
    paths:
      - "!**.md"
      - "!.gitignore"
      - "!LICENSE"
      - "!.github/workflows/**"
      - ".github/workflows/on-pr.yml"
      - ".github/workflows/tests.yml"
      - "**"
  schedule:
    - cron: '0 13 * * *' # Must be single quotes!!
jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          do_not_skip: '["workflow_dispatch", "schedule"]'
  trigger-tests:
    uses: ./.github/workflows/generic-testing.yml
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    needs: pre_job
    with:
      stack-orchestrator-ref: ${{ github.event.inputs.stack-orchestrator-ref }}
      ipld-eth-beacon-db-ref: ${{ github.event.inputs.ipld-eth-beacon-db-ref }}
      ssz-data-ref: ${{ github.event.inputs.ssz-data-ref }}
    secrets:
      GHA_KEY: ${{secrets.GHA_KEY}}
  system-testing:
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    needs: pre_job
    uses: ./.github/workflows/system-tests.yml
    with:
      stack-orchestrator-ref: ${{ github.event.inputs.stack-orchestrator-ref }}
      ipld-eth-beacon-db-ref: ${{ github.event.inputs.ipld-eth-beacon-db-ref }}
    secrets:
      GHA_KEY: ${{secrets.GHA_KEY}}
      BC_ADDRESS: ${{secrets.BC_ADDRESS}}
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    needs:
      - trigger-tests
      - system-testing
    if: |
      always() &&
      (needs.trigger-tests.result == 'success' || needs.trigger-tests.result == 'skipped') &&
      (needs.system-testing.result == 'success' || needs.system-testing.result == 'skipped') &&
      github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
      - name: Run docker build
        run: make docker-build
      - name: Tag docker image
        run: docker tag vulcanize/ipld-eth-beacon-indexer docker.pkg.github.com/vulcanize/ipld-eth-beacon-indexer/ipld-eth-beacon-indexer:${{steps.vars.outputs.sha}}
      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u vulcanize --password-stdin
      - name: Docker Push
        run: docker push docker.pkg.github.com/vulcanize/ipld-eth-beacon-indexer/ipld-eth-beacon-indexer:${{steps.vars.outputs.sha}}
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: |
      always() &&
      (needs.build.result == 'success') &&
      github.event_name == 'release'
    steps:
      - name: Get the version
        id: vars
        run: |
          echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
          echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})
      - name: Docker Login to Github Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u vulcanize --password-stdin
      - name: Docker Pull
        run: docker pull docker.pkg.github.com/vulcanize/ipld-eth-beacon-indexer/ipld-eth-beacon-indexer:${{steps.vars.outputs.sha}}
      - name: Docker Login to Docker Registry
        run: echo ${{ secrets.VULCANIZEJENKINS_PAT }} | docker login -u vulcanizejenkins --password-stdin
      - name: Tag docker image
        run: docker tag docker.pkg.github.com/vulcanize/ipld-eth-beacon-indexer/ipld-eth-beacon-indexer:${{steps.vars.outputs.sha}} vulcanize/ipld-eth-beacon-indexer:${{steps.vars.outputs.tag}}
      - name: Docker Push to Docker Hub
        run: docker push vulcanize/ipld-eth-beacon-indexer:${{steps.vars.outputs.tag}}
